version: '3.8'

services:
  ai_check_photo:
    build: ai_check_photo
    container_name: definition_text
    restart: unless-stopped
    environment:
      - RABBITMQ_HOST
      - RABBITMQ_PORT
      - RABBITMQ_LOGIN
      - RABBITMQ_PASSWORD
      - PYTHONUNBUFFERED=1
    volumes:
      - ./ai_check_photo/resnet-152-text-detector-ai:/app/resnet-152-text-detector-ai
    networks:
      - basic-network


networks:
  basic-network: